import * as github from '@actions/github';
import {
  DiffResult,
  DiffSummary,
  PairwiseDiffResult,
  EnvironmentPair,
  EdgeFunction,
  RlsPolicy,
  SqlFunction,
  TableSchema,
} from '../types';

const COMMENT_MARKER = '<!-- supabase-diff-action -->';

export async function postPrComment(
  token: string,
  summary: DiffSummary
): Promise<void> {
  const octokit = github.getOctokit(token);
  const context = github.context;

  if (!context.payload.pull_request) {
    console.log('Not a pull request, skipping comment');
    return;
  }

  const prNumber = context.payload.pull_request.number;
  const { owner, repo } = context.repo;

  const body = buildCommentBody(summary);

  const { data: comments } = await octokit.rest.issues.listComments({
    owner,
    repo,
    issue_number: prNumber,
  });

  const existingComment = comments.find((comment) =>
    comment.body?.includes(COMMENT_MARKER)
  );

  if (existingComment) {
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: existingComment.id,
      body,
    });
  } else {
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body,
    });
  }
}

interface DiffCounts {
  onlyInSource: number;
  onlyInTarget: number;
  different: number;
  total: number;
}

function countDiffsFromResult<T>(diff: DiffResult<T>): DiffCounts {
  const onlyInSource = diff.onlyInDev.length;
  const onlyInTarget = diff.onlyInPrd.length;
  const different = diff.different.length;
  return {
    onlyInSource,
    onlyInTarget,
    different,
    total: onlyInSource + onlyInTarget + different,
  };
}

function countDiffsFromPairwise<T>(
  diffs: PairwiseDiffResult<T>[] | undefined
): DiffCounts {
  if (!diffs || diffs.length === 0) {
    return { onlyInSource: 0, onlyInTarget: 0, different: 0, total: 0 };
  }
  let onlyInSource = 0;
  let onlyInTarget = 0;
  let different = 0;
  for (const d of diffs) {
    onlyInSource += d.result.onlyInDev.length;
    onlyInTarget += d.result.onlyInPrd.length;
    different += d.result.different.length;
  }
  return {
    onlyInSource,
    onlyInTarget,
    different,
    total: onlyInSource + onlyInTarget + different,
  };
}

function getPairLabel(pair: EnvironmentPair): { source: string; target: string } {
  switch (pair) {
    case 'dev-stg':
      return { source: 'Dev', target: 'Stg' };
    case 'stg-prd':
      return { source: 'Stg', target: 'Prd' };
    case 'dev-prd':
      return { source: 'Dev', target: 'Prd' };
  }
}

function buildCommentBody(summary: DiffSummary): string {
  const lines: string[] = [COMMENT_MARKER];

  lines.push('## 📊 Supabase Environment Diff');
  lines.push('');

  if (summary.hasStg) {
    lines.push('> Comparing: **Dev** → **Stg** → **Prd**');
  } else {
    lines.push('> Comparing: **Dev** → **Prd**');
  }
  lines.push('');

  const edgeCounts = countDiffsFromPairwise(summary.edgeFunctions);
  const rlsCounts = countDiffsFromPairwise(summary.rlsPolicies);
  const sqlCounts = countDiffsFromPairwise(summary.sqlFunctions);
  const schemaCounts = countDiffsFromPairwise(summary.schemas);

  lines.push('| Category | Status | Differences |');
  lines.push('|----------|--------|-------------|');
  lines.push(buildSummaryRow('Edge Functions', edgeCounts));
  lines.push(buildSummaryRow('RLS Policies', rlsCounts));
  lines.push(buildSummaryRow('SQL Functions', sqlCounts));
  lines.push(buildSummaryRow('Schemas', schemaCounts));
  lines.push('');

  if (!summary.hasDiff) {
    lines.push('✅ **All environments are in sync.**');
    lines.push('');
    lines.push('---');
    lines.push('*Generated by supabase-diff-action*');
    return lines.join('\n');
  }

  lines.push('---');
  lines.push('');

  if (summary.edgeFunctions && edgeCounts.total > 0) {
    lines.push(...buildEdgeFunctionsSection(summary.edgeFunctions));
  }

  if (summary.rlsPolicies && rlsCounts.total > 0) {
    lines.push(...buildRlsPoliciesSection(summary.rlsPolicies));
  }

  if (summary.sqlFunctions && sqlCounts.total > 0) {
    lines.push(...buildSqlFunctionsSection(summary.sqlFunctions));
  }

  if (summary.schemas && schemaCounts.total > 0) {
    lines.push(...buildSchemasSection(summary.schemas));
  }

  lines.push('---');
  lines.push('*Generated by supabase-diff-action*');

  return lines.join('\n');
}

function buildSummaryRow(category: string, counts: DiffCounts): string {
  if (counts.total === 0) {
    return `| ${category} | ✅ Synced | 0 |`;
  }

  const details: string[] = [];
  if (counts.onlyInSource > 0) details.push(`🆕 ${counts.onlyInSource}`);
  if (counts.onlyInTarget > 0) details.push(`🗑️ ${counts.onlyInTarget}`);
  if (counts.different > 0) details.push(`🔄 ${counts.different}`);

  return `| ${category} | ⚠️ Differences | ${details.join(' ')} |`;
}

function buildEdgeFunctionsSection(
  diffs: PairwiseDiffResult<EdgeFunction>[]
): string[] {
  const lines: string[] = [];

  lines.push('<details>');
  lines.push('<summary><strong>Edge Functions</strong></summary>');
  lines.push('');

  for (const { pair, result } of diffs) {
    const counts = countDiffsFromResult(result);
    if (counts.total === 0) continue;

    const label = getPairLabel(pair);
    lines.push(`### ${label.source} → ${label.target}`);
    lines.push('');

    if (result.onlyInDev.length > 0) {
      lines.push(`#### 🆕 Only in ${label.source} (${result.onlyInDev.length})`);
      lines.push('');
      lines.push('| Function | Version | Status |');
      lines.push('|----------|---------|--------|');
      for (const fn of result.onlyInDev) {
        lines.push(`| \`${fn.slug}\` | v${fn.version} | ${fn.status} |`);
      }
      lines.push('');
    }

    if (result.onlyInPrd.length > 0) {
      lines.push(
        `#### 🗑️ Only in ${label.target} (${result.onlyInPrd.length})`
      );
      lines.push('');
      lines.push('| Function | Version | Status |');
      lines.push('|----------|---------|--------|');
      for (const fn of result.onlyInPrd) {
        lines.push(`| \`${fn.slug}\` | v${fn.version} | ${fn.status} |`);
      }
      lines.push('');
    }

    if (result.different.length > 0) {
      lines.push(`#### 🔄 Different (${result.different.length})`);
      lines.push('> Both environments have this item, but with differences');
      lines.push('');
      lines.push(`| Function | ${label.source} | ${label.target} | Difference |`);
      lines.push('|----------|-----|------|------------|');
      for (const { dev, prd, differences } of result.different) {
        lines.push(
          `| \`${dev.slug}\` | v${dev.version} | v${prd.version} | ${differences.join(', ')} |`
        );
      }
      lines.push('');
    }
  }

  lines.push('</details>');
  lines.push('');
  return lines;
}

function buildRlsPoliciesSection(
  diffs: PairwiseDiffResult<RlsPolicy>[]
): string[] {
  const lines: string[] = [];

  lines.push('<details>');
  lines.push('<summary><strong>RLS Policies</strong></summary>');
  lines.push('');

  for (const { pair, result } of diffs) {
    const counts = countDiffsFromResult(result);
    if (counts.total === 0) continue;

    const label = getPairLabel(pair);
    lines.push(`### ${label.source} → ${label.target}`);
    lines.push('');

    if (result.onlyInDev.length > 0) {
      lines.push(`#### 🆕 Only in ${label.source} (${result.onlyInDev.length})`);
      lines.push('');
      lines.push('| Table | Policy | Command | Roles |');
      lines.push('|-------|--------|---------|-------|');
      for (const policy of result.onlyInDev) {
        lines.push(
          `| \`${policy.schemaName}.${policy.tableName}\` | \`${policy.policyName}\` | ${policy.cmd} | ${policy.roles.join(', ')} |`
        );
      }
      lines.push('');
    }

    if (result.onlyInPrd.length > 0) {
      lines.push(
        `#### 🗑️ Only in ${label.target} (${result.onlyInPrd.length})`
      );
      lines.push('');
      lines.push('| Table | Policy | Command | Roles |');
      lines.push('|-------|--------|---------|-------|');
      for (const policy of result.onlyInPrd) {
        lines.push(
          `| \`${policy.schemaName}.${policy.tableName}\` | \`${policy.policyName}\` | ${policy.cmd} | ${policy.roles.join(', ')} |`
        );
      }
      lines.push('');
    }

    if (result.different.length > 0) {
      lines.push(`#### 🔄 Different (${result.different.length})`);
      lines.push('> Both environments have this policy, but with differences');
      lines.push('');
      lines.push('| Table | Policy | Difference |');
      lines.push('|-------|--------|------------|');
      for (const { dev, differences } of result.different) {
        lines.push(
          `| \`${dev.schemaName}.${dev.tableName}\` | \`${dev.policyName}\` | ${differences.join(', ')} |`
        );
      }
      lines.push('');
    }
  }

  lines.push('</details>');
  lines.push('');
  return lines;
}

function buildSqlFunctionsSection(
  diffs: PairwiseDiffResult<SqlFunction>[]
): string[] {
  const lines: string[] = [];

  lines.push('<details>');
  lines.push('<summary><strong>SQL Functions</strong></summary>');
  lines.push('');

  for (const { pair, result } of diffs) {
    const counts = countDiffsFromResult(result);
    if (counts.total === 0) continue;

    const label = getPairLabel(pair);
    lines.push(`### ${label.source} → ${label.target}`);
    lines.push('');

    if (result.onlyInDev.length > 0) {
      lines.push(`#### 🆕 Only in ${label.source} (${result.onlyInDev.length})`);
      lines.push('');
      lines.push('| Schema | Function | Return Type | Language |');
      lines.push('|--------|----------|-------------|----------|');
      for (const fn of result.onlyInDev) {
        const signature = `${fn.functionName}(${fn.arguments})`;
        lines.push(
          `| \`${fn.schemaName}\` | \`${signature}\` | ${fn.returnType} | ${fn.language} |`
        );
      }
      lines.push('');
    }

    if (result.onlyInPrd.length > 0) {
      lines.push(
        `#### 🗑️ Only in ${label.target} (${result.onlyInPrd.length})`
      );
      lines.push('');
      lines.push('| Schema | Function | Return Type | Language |');
      lines.push('|--------|----------|-------------|----------|');
      for (const fn of result.onlyInPrd) {
        const signature = `${fn.functionName}(${fn.arguments})`;
        lines.push(
          `| \`${fn.schemaName}\` | \`${signature}\` | ${fn.returnType} | ${fn.language} |`
        );
      }
      lines.push('');
    }

    if (result.different.length > 0) {
      lines.push(`#### 🔄 Different (${result.different.length})`);
      lines.push(
        '> Both environments have this function, but with differences'
      );
      lines.push('');
      lines.push('| Schema | Function | Difference |');
      lines.push('|--------|----------|------------|');
      for (const { dev, differences } of result.different) {
        const signature = `${dev.functionName}(${dev.arguments})`;
        lines.push(
          `| \`${dev.schemaName}\` | \`${signature}\` | ${differences.join(', ')} |`
        );
      }
      lines.push('');
    }
  }

  lines.push('</details>');
  lines.push('');
  return lines;
}

function buildSchemasSection(
  diffs: PairwiseDiffResult<TableSchema>[]
): string[] {
  const lines: string[] = [];

  lines.push('<details>');
  lines.push('<summary><strong>Schemas</strong></summary>');
  lines.push('');

  for (const { pair, result } of diffs) {
    const counts = countDiffsFromResult(result);
    if (counts.total === 0) continue;

    const label = getPairLabel(pair);
    lines.push(`### ${label.source} → ${label.target}`);
    lines.push('');

    if (result.onlyInDev.length > 0) {
      lines.push(`#### 🆕 Only in ${label.source} (${result.onlyInDev.length})`);
      lines.push('');
      lines.push('| Schema | Table | Columns |');
      lines.push('|--------|-------|---------|');
      for (const schema of result.onlyInDev) {
        lines.push(
          `| \`${schema.schemaName}\` | \`${schema.tableName}\` | ${schema.columns.length} |`
        );
      }
      lines.push('');
    }

    if (result.onlyInPrd.length > 0) {
      lines.push(
        `#### 🗑️ Only in ${label.target} (${result.onlyInPrd.length})`
      );
      lines.push('');
      lines.push('| Schema | Table | Columns |');
      lines.push('|--------|-------|---------|');
      for (const schema of result.onlyInPrd) {
        lines.push(
          `| \`${schema.schemaName}\` | \`${schema.tableName}\` | ${schema.columns.length} |`
        );
      }
      lines.push('');
    }

    if (result.different.length > 0) {
      lines.push(`#### 🔄 Different (${result.different.length})`);
      lines.push('> Both environments have this table, but with differences');
      lines.push('');
      for (const { dev, differences } of result.different) {
        lines.push(`<details>`);
        lines.push(
          `<summary><code>${dev.schemaName}.${dev.tableName}</code></summary>`
        );
        lines.push('');
        lines.push('| Type | Difference |');
        lines.push('|------|------------|');
        for (const d of differences) {
          lines.push(`| ${categorizeChange(d)} | ${d} |`);
        }
        lines.push('');
        lines.push('</details>');
        lines.push('');
      }
    }
  }

  lines.push('</details>');
  lines.push('');
  return lines;
}

function categorizeChange(diff: string): string {
  if (diff.includes('column')) return '📊 Column';
  if (diff.includes('index')) return '📇 Index';
  if (diff.includes('constraint')) return '🔗 Constraint';
  return '📝 Other';
}
