import * as github from '@actions/github';
import {
  DiffResult,
  DiffSummary,
  EdgeFunction,
  RlsPolicy,
  SqlFunction,
  TableSchema,
} from '../types';

const COMMENT_MARKER = '<!-- supabase-diff-action -->';

export async function postPrComment(
  token: string,
  summary: DiffSummary
): Promise<void> {
  const octokit = github.getOctokit(token);
  const context = github.context;

  if (!context.payload.pull_request) {
    console.log('Not a pull request, skipping comment');
    return;
  }

  const prNumber = context.payload.pull_request.number;
  const { owner, repo } = context.repo;

  const body = buildCommentBody(summary);

  const { data: comments } = await octokit.rest.issues.listComments({
    owner,
    repo,
    issue_number: prNumber,
  });

  const existingComment = comments.find(
    (comment) => comment.body?.includes(COMMENT_MARKER)
  );

  if (existingComment) {
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: existingComment.id,
      body,
    });
  } else {
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body,
    });
  }
}

interface DiffCounts {
  onlyInDev: number;
  onlyInPrd: number;
  different: number;
  total: number;
}

function countDiffs<T>(diff: DiffResult<T> | undefined): DiffCounts {
  if (!diff) {
    return { onlyInDev: 0, onlyInPrd: 0, different: 0, total: 0 };
  }
  const onlyInDev = diff.onlyInDev.length;
  const onlyInPrd = diff.onlyInPrd.length;
  const different = diff.different.length;
  return {
    onlyInDev,
    onlyInPrd,
    different,
    total: onlyInDev + onlyInPrd + different,
  };
}

function buildCommentBody(summary: DiffSummary): string {
  const lines: string[] = [COMMENT_MARKER];

  lines.push('## 📊 Supabase Environment Diff');
  lines.push('');

  // Build summary table
  const edgeCounts = countDiffs(summary.edgeFunctions);
  const rlsCounts = countDiffs(summary.rlsPolicies);
  const sqlCounts = countDiffs(summary.sqlFunctions);
  const schemaCounts = countDiffs(summary.schemas);

  lines.push('| Category | Status | Differences |');
  lines.push('|----------|--------|-------------|');
  lines.push(buildSummaryRow('Edge Functions', edgeCounts));
  lines.push(buildSummaryRow('RLS Policies', rlsCounts));
  lines.push(buildSummaryRow('SQL Functions', sqlCounts));
  lines.push(buildSummaryRow('Schemas', schemaCounts));
  lines.push('');

  if (!summary.hasDiff) {
    lines.push('✅ **Dev and prod environments are in sync.**');
    lines.push('');
    lines.push('---');
    lines.push('*Generated by supabase-diff-action*');
    return lines.join('\n');
  }

  lines.push('---');
  lines.push('');

  if (summary.edgeFunctions && edgeCounts.total > 0) {
    lines.push(...buildEdgeFunctionsSection(summary.edgeFunctions));
  }

  if (summary.rlsPolicies && rlsCounts.total > 0) {
    lines.push(...buildRlsPoliciesSection(summary.rlsPolicies));
  }

  if (summary.sqlFunctions && sqlCounts.total > 0) {
    lines.push(...buildSqlFunctionsSection(summary.sqlFunctions));
  }

  if (summary.schemas && schemaCounts.total > 0) {
    lines.push(...buildSchemasSection(summary.schemas));
  }

  lines.push('---');
  lines.push('*Generated by supabase-diff-action*');

  return lines.join('\n');
}

function buildSummaryRow(category: string, counts: DiffCounts): string {
  if (counts.total === 0) {
    return `| ${category} | ✅ Synced | 0 |`;
  }

  const details: string[] = [];
  if (counts.onlyInDev > 0) details.push(`🆕 ${counts.onlyInDev}`);
  if (counts.onlyInPrd > 0) details.push(`🗑️ ${counts.onlyInPrd}`);
  if (counts.different > 0) details.push(`🔄 ${counts.different}`);

  return `| ${category} | ⚠️ Differences | ${details.join(' ')} |`;
}

function buildEdgeFunctionsSection(
  diff: DiffResult<EdgeFunction>
): string[] {
  const lines: string[] = [];

  lines.push('<details>');
  lines.push('<summary><strong>Edge Functions</strong></summary>');
  lines.push('');

  if (diff.onlyInDev.length > 0) {
    lines.push(`#### 🆕 Only in Dev (${diff.onlyInDev.length})`);
    lines.push('');
    lines.push('| Function | Version | Status |');
    lines.push('|----------|---------|--------|');
    for (const fn of diff.onlyInDev) {
      lines.push(`| \`${fn.slug}\` | v${fn.version} | ${fn.status} |`);
    }
    lines.push('');
  }

  if (diff.onlyInPrd.length > 0) {
    lines.push(`#### 🗑️ Only in Prd (${diff.onlyInPrd.length})`);
    lines.push('');
    lines.push('| Function | Version | Status |');
    lines.push('|----------|---------|--------|');
    for (const fn of diff.onlyInPrd) {
      lines.push(`| \`${fn.slug}\` | v${fn.version} | ${fn.status} |`);
    }
    lines.push('');
  }

  if (diff.different.length > 0) {
    lines.push(`#### 🔄 Changed (${diff.different.length})`);
    lines.push('');
    lines.push('| Function | Dev | Prod | Difference |');
    lines.push('|----------|-----|------|------------|');
    for (const { dev, prd, differences } of diff.different) {
      lines.push(
        `| \`${dev.slug}\` | v${dev.version} | v${prd.version} | ${differences.join(', ')} |`
      );
    }
    lines.push('');
  }

  lines.push('</details>');
  lines.push('');
  return lines;
}

function buildRlsPoliciesSection(diff: DiffResult<RlsPolicy>): string[] {
  const lines: string[] = [];

  lines.push('<details>');
  lines.push('<summary><strong>RLS Policies</strong></summary>');
  lines.push('');

  if (diff.onlyInDev.length > 0) {
    lines.push(`#### 🆕 Only in Dev (${diff.onlyInDev.length})`);
    lines.push('');
    lines.push('| Table | Policy | Command | Roles |');
    lines.push('|-------|--------|---------|-------|');
    for (const policy of diff.onlyInDev) {
      lines.push(
        `| \`${policy.schemaName}.${policy.tableName}\` | \`${policy.policyName}\` | ${policy.cmd} | ${policy.roles.join(', ')} |`
      );
    }
    lines.push('');
  }

  if (diff.onlyInPrd.length > 0) {
    lines.push(`#### 🗑️ Only in Prd (${diff.onlyInPrd.length})`);
    lines.push('');
    lines.push('| Table | Policy | Command | Roles |');
    lines.push('|-------|--------|---------|-------|');
    for (const policy of diff.onlyInPrd) {
      lines.push(
        `| \`${policy.schemaName}.${policy.tableName}\` | \`${policy.policyName}\` | ${policy.cmd} | ${policy.roles.join(', ')} |`
      );
    }
    lines.push('');
  }

  if (diff.different.length > 0) {
    lines.push(`#### 🔄 Changed (${diff.different.length})`);
    lines.push('');
    lines.push('| Table | Policy | Difference |');
    lines.push('|-------|--------|------------|');
    for (const { dev, differences } of diff.different) {
      lines.push(
        `| \`${dev.schemaName}.${dev.tableName}\` | \`${dev.policyName}\` | ${differences.join(', ')} |`
      );
    }
    lines.push('');
  }

  lines.push('</details>');
  lines.push('');
  return lines;
}

function buildSqlFunctionsSection(
  diff: DiffResult<SqlFunction>
): string[] {
  const lines: string[] = [];

  lines.push('<details>');
  lines.push('<summary><strong>SQL Functions</strong></summary>');
  lines.push('');

  if (diff.onlyInDev.length > 0) {
    lines.push(`#### 🆕 Only in Dev (${diff.onlyInDev.length})`);
    lines.push('');
    lines.push('| Schema | Function | Return Type | Language |');
    lines.push('|--------|----------|-------------|----------|');
    for (const fn of diff.onlyInDev) {
      const signature = `${fn.functionName}(${fn.arguments})`;
      lines.push(
        `| \`${fn.schemaName}\` | \`${signature}\` | ${fn.returnType} | ${fn.language} |`
      );
    }
    lines.push('');
  }

  if (diff.onlyInPrd.length > 0) {
    lines.push(`#### 🗑️ Only in Prd (${diff.onlyInPrd.length})`);
    lines.push('');
    lines.push('| Schema | Function | Return Type | Language |');
    lines.push('|--------|----------|-------------|----------|');
    for (const fn of diff.onlyInPrd) {
      const signature = `${fn.functionName}(${fn.arguments})`;
      lines.push(
        `| \`${fn.schemaName}\` | \`${signature}\` | ${fn.returnType} | ${fn.language} |`
      );
    }
    lines.push('');
  }

  if (diff.different.length > 0) {
    lines.push(`#### 🔄 Changed (${diff.different.length})`);
    lines.push('');
    lines.push('| Schema | Function | Difference |');
    lines.push('|--------|----------|------------|');
    for (const { dev, differences } of diff.different) {
      const signature = `${dev.functionName}(${dev.arguments})`;
      lines.push(
        `| \`${dev.schemaName}\` | \`${signature}\` | ${differences.join(', ')} |`
      );
    }
    lines.push('');
  }

  lines.push('</details>');
  lines.push('');
  return lines;
}

function buildSchemasSection(diff: DiffResult<TableSchema>): string[] {
  const lines: string[] = [];

  lines.push('<details>');
  lines.push('<summary><strong>Schemas</strong></summary>');
  lines.push('');

  if (diff.onlyInDev.length > 0) {
    lines.push(`#### 🆕 Only in Dev (${diff.onlyInDev.length})`);
    lines.push('');
    lines.push('| Schema | Table | Columns |');
    lines.push('|--------|-------|---------|');
    for (const schema of diff.onlyInDev) {
      lines.push(
        `| \`${schema.schemaName}\` | \`${schema.tableName}\` | ${schema.columns.length} |`
      );
    }
    lines.push('');
  }

  if (diff.onlyInPrd.length > 0) {
    lines.push(`#### 🗑️ Only in Prd (${diff.onlyInPrd.length})`);
    lines.push('');
    lines.push('| Schema | Table | Columns |');
    lines.push('|--------|-------|---------|');
    for (const schema of diff.onlyInPrd) {
      lines.push(
        `| \`${schema.schemaName}\` | \`${schema.tableName}\` | ${schema.columns.length} |`
      );
    }
    lines.push('');
  }

  if (diff.different.length > 0) {
    lines.push(`#### 🔄 Changed (${diff.different.length})`);
    lines.push('');
    for (const { dev, differences } of diff.different) {
      lines.push(`<details>`);
      lines.push(`<summary><code>${dev.schemaName}.${dev.tableName}</code></summary>`);
      lines.push('');
      lines.push('| Type | Difference |');
      lines.push('|------|------------|');
      for (const d of differences) {
        lines.push(`| ${categorizeChange(d)} | ${d} |`);
      }
      lines.push('');
      lines.push('</details>');
      lines.push('');
    }
  }

  lines.push('</details>');
  lines.push('');
  return lines;
}

function categorizeChange(diff: string): string {
  if (diff.includes('column')) return '📊 Column';
  if (diff.includes('index')) return '📇 Index';
  if (diff.includes('constraint')) return '🔗 Constraint';
  return '📝 Other';
}
