import * as github from '@actions/github';
import {
  DiffResult,
  DiffSummary,
  EdgeFunction,
  RlsPolicy,
  SqlFunction,
  TableSchema,
} from '../types';

const COMMENT_MARKER = '<!-- supabase-diff-action -->';

export async function postPrComment(
  token: string,
  summary: DiffSummary
): Promise<void> {
  const octokit = github.getOctokit(token);
  const context = github.context;

  if (!context.payload.pull_request) {
    console.log('Not a pull request, skipping comment');
    return;
  }

  const prNumber = context.payload.pull_request.number;
  const { owner, repo } = context.repo;

  const body = buildCommentBody(summary);

  const { data: comments } = await octokit.rest.issues.listComments({
    owner,
    repo,
    issue_number: prNumber,
  });

  const existingComment = comments.find(
    (comment) => comment.body?.includes(COMMENT_MARKER)
  );

  if (existingComment) {
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: existingComment.id,
      body,
    });
  } else {
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body,
    });
  }
}

function buildCommentBody(summary: DiffSummary): string {
  const lines: string[] = [COMMENT_MARKER];

  if (summary.hasDiff) {
    lines.push('## Supabase Environment Diff');
    lines.push('');
    lines.push('Differences detected between dev and prod environments.');
    lines.push('');
  } else {
    lines.push('## Supabase Environment Diff');
    lines.push('');
    lines.push('Dev and prod environments are in sync.');
    lines.push('');
    return lines.join('\n');
  }

  if (summary.edgeFunctions) {
    lines.push(...buildEdgeFunctionsSection(summary.edgeFunctions));
  }

  if (summary.rlsPolicies) {
    lines.push(...buildRlsPoliciesSection(summary.rlsPolicies));
  }

  if (summary.sqlFunctions) {
    lines.push(...buildSqlFunctionsSection(summary.sqlFunctions));
  }

  if (summary.schemas) {
    lines.push(...buildSchemasSection(summary.schemas));
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by supabase-diff-action*');

  return lines.join('\n');
}

function buildEdgeFunctionsSection(
  diff: DiffResult<EdgeFunction>
): string[] {
  const lines: string[] = [];
  const hasDiff =
    diff.onlyInDev.length > 0 ||
    diff.onlyInPrd.length > 0 ||
    diff.different.length > 0;

  if (!hasDiff) {
    lines.push('### Edge Functions');
    lines.push('No differences');
    lines.push('');
    return lines;
  }

  lines.push('### Edge Functions');
  lines.push('');
  lines.push('| Function | dev | prod | Status |');
  lines.push('|----------|-----|------|--------|');

  for (const fn of diff.onlyInDev) {
    lines.push(`| ${fn.slug} | v${fn.version} | - | Only in dev |`);
  }

  for (const fn of diff.onlyInPrd) {
    lines.push(`| ${fn.slug} | - | v${fn.version} | Only in prod |`);
  }

  for (const { dev, prd, differences } of diff.different) {
    lines.push(
      `| ${dev.slug} | v${dev.version} | v${prd.version} | ${differences.join(', ')} |`
    );
  }

  lines.push('');
  return lines;
}

function buildRlsPoliciesSection(diff: DiffResult<RlsPolicy>): string[] {
  const lines: string[] = [];
  const hasDiff =
    diff.onlyInDev.length > 0 ||
    diff.onlyInPrd.length > 0 ||
    diff.different.length > 0;

  if (!hasDiff) {
    lines.push('### RLS Policies');
    lines.push('No differences');
    lines.push('');
    return lines;
  }

  lines.push('### RLS Policies');
  lines.push('');
  lines.push('| Table | Policy | dev | prod | Status |');
  lines.push('|-------|--------|-----|------|--------|');

  for (const policy of diff.onlyInDev) {
    lines.push(
      `| ${policy.schemaName}.${policy.tableName} | ${policy.policyName} | ✓ | - | Only in dev |`
    );
  }

  for (const policy of diff.onlyInPrd) {
    lines.push(
      `| ${policy.schemaName}.${policy.tableName} | ${policy.policyName} | - | ✓ | Only in prod |`
    );
  }

  for (const { dev, differences } of diff.different) {
    lines.push(
      `| ${dev.schemaName}.${dev.tableName} | ${dev.policyName} | ✓ | ✓ | ${differences.join(', ')} |`
    );
  }

  lines.push('');
  return lines;
}

function buildSqlFunctionsSection(
  diff: DiffResult<SqlFunction>
): string[] {
  const lines: string[] = [];
  const hasDiff =
    diff.onlyInDev.length > 0 ||
    diff.onlyInPrd.length > 0 ||
    diff.different.length > 0;

  if (!hasDiff) {
    lines.push('### SQL Functions');
    lines.push('No differences');
    lines.push('');
    return lines;
  }

  lines.push('### SQL Functions');
  lines.push('');
  lines.push('| Schema | Function | dev | prod | Status |');
  lines.push('|--------|----------|-----|------|--------|');

  for (const fn of diff.onlyInDev) {
    const signature = `${fn.functionName}(${fn.arguments})`;
    lines.push(`| ${fn.schemaName} | ${signature} | ✓ | - | Only in dev |`);
  }

  for (const fn of diff.onlyInPrd) {
    const signature = `${fn.functionName}(${fn.arguments})`;
    lines.push(`| ${fn.schemaName} | ${signature} | - | ✓ | Only in prod |`);
  }

  for (const { dev, differences } of diff.different) {
    const signature = `${dev.functionName}(${dev.arguments})`;
    lines.push(
      `| ${dev.schemaName} | ${signature} | ✓ | ✓ | ${differences.join(', ')} |`
    );
  }

  lines.push('');
  return lines;
}

function buildSchemasSection(diff: DiffResult<TableSchema>): string[] {
  const lines: string[] = [];
  const hasDiff =
    diff.onlyInDev.length > 0 ||
    diff.onlyInPrd.length > 0 ||
    diff.different.length > 0;

  if (!hasDiff) {
    lines.push('### Schemas');
    lines.push('No differences');
    lines.push('');
    return lines;
  }

  lines.push('### Schemas');
  lines.push('');
  lines.push('| Schema | Table | dev | prod | Status |');
  lines.push('|--------|-------|-----|------|--------|');

  for (const schema of diff.onlyInDev) {
    lines.push(
      `| ${schema.schemaName} | ${schema.tableName} | ✓ | - | Only in dev |`
    );
  }

  for (const schema of diff.onlyInPrd) {
    lines.push(
      `| ${schema.schemaName} | ${schema.tableName} | - | ✓ | Only in prod |`
    );
  }

  for (const { dev } of diff.different) {
    lines.push(
      `| ${dev.schemaName} | ${dev.tableName} | ✓ | ✓ | Has differences |`
    );
  }

  lines.push('');

  if (diff.different.length > 0) {
    lines.push('<details>');
    lines.push('<summary>Diff Details</summary>');
    lines.push('');

    for (const { dev, differences } of diff.different) {
      lines.push(`#### ${dev.schemaName}.${dev.tableName}`);
      lines.push('');
      for (const d of differences) {
        lines.push(`- ${d}`);
      }
      lines.push('');
    }

    lines.push('</details>');
    lines.push('');
  }

  return lines;
}
